In [6]:
import numpy as np
import numpy.random as random
import scipy as sp
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
%precision 3
sample = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#インデックス参照
#スライス操作
sample_slice = sample[0:5]
print(sample)
print(sample_slice)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [12]:
#参照しているため、オリジナルの配列の値も置き換わる
sample_slice[0:2] = 10
print(sample)
print(sample_slice)

[10 10  2  3  4  5  6  7  8  9]
[10 10  2  3  4]


In [13]:
#別の配列にコピーしておけば大丈夫
sample_copy = np.copy(sample)
print(sample_copy)
sample_copy[0:3] = 20
print(sample_copy)
print(sample)

[10 10  2  3  4  5  6  7  8  9]
[20 20 20  3  4  5  6  7  8  9]
[10 10  2  3  4  5  6  7  8  9]


In [24]:
#ブールインデックス参照
sample_2 = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5, 5) # randn - 正規分布の乱数生成
print(sample_2)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [17]:
#配列の要素値を論理演算子でT/F判定
sample_2 == 'a'

array([ True, False, False, False,  True])

In [25]:
#判定結果がTrueとなる要素のインデックスが返されるので、それを別の配列から値を取り出すためのインデックスに指定
data_2 = data[sample_2 == 'a'] #デフォルトは行インデックス
print(data_2)

[[ 1.764  0.4    0.979  2.241  1.868]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [32]:
data_3 = data[:, sample_2 == 'a'] #列インデックスもできる
print(data_3)

[[ 1.764  1.868]
 [-0.977  0.411]
 [ 0.144  0.444]
 [ 0.334 -0.854]
 [-2.553  2.27 ]]


In [35]:
#条件制御
# numpy.where(array_consition(boolean), array_true, array_false)
condition = np.array([True,True,False,False,True])
array_t = ([1,2,3,4,5]) # Trueのときの配列
array_f = ([100,200,300,400,500]) # Falseのときの配列
array_judge = np.where(condition, array_t, array_f)
print(array_judge)

[  1   2 300 400   5]


In [36]:
#重複削除
# numpy.unique(array)
print(condition)
print(np.unique(condition))

[ True  True False False  True]
[False  True]


In [39]:
#ユニバーサル関数　すべての要素に適用
sample_3 = np.arange(20)
print(np.sqrt(sample_3))
print(np.exp(sample_3))

[0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.    3.162 3.317
 3.464 3.606 3.742 3.873 4.    4.123 4.243 4.359]
[1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03 2.203e+04 5.987e+04 1.628e+05 4.424e+05
 1.203e+06 3.269e+06 8.886e+06 2.415e+07 6.566e+07 1.785e+08]


In [43]:
#配列の最大、最小、平均、合計
sample_4 = np.arange(9).reshape(3,3)
print(sample_4)
print(sample_4.max())
print(sample_4.min())
print(sample_4.mean())
print(sample_4.sum())
print(sample_4.max(axis=0))
print(sample_4.min(axis=1))
print(sample_4.sum(axis=0))
print(sample_4.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
0
4.0
36
[6 7 8]
[0 3 6]
[ 9 12 15]
[ 3 12 21]


In [48]:
#配列の要素の真偽値判定　any - いずれか1つ, all - すべて
print(condition.any())
print(condition.all())
#条件を指定してからsum.()で合致する要素の個数がわかる
print((sample_4 > 5).sum())

True
False
3


In [50]:
#対角成分の計算 diag, trace
print(np.diag(sample_4)) #対角成分の抽出
print(np.trace(sample_4)) #対角成分の和

[0 4 8]
12


In [70]:
#配列の結合 concatenate, vstack, hstack
sample_5 = np.arange(1,7).reshape(2,3)
sample_6 = np.arange(7,13).reshape(2,3)
print(sample_5)
print(sample_6)
#行方向に結合 concatenate(array1, array2, axis=0)
row_concat = np.concatenate([sample_5, sample_6], axis=0)
print(row_concat)
#列方向に結合 concatenate(array1, array2, axis=1)
col_concat = np.concatenate([sample_5, sample_6], axis=1)
print(col_concat)
#行方向に結合 vstack(array1, array2)
row_stack = np.vstack((sample_5, sample_6))
print(row_stack)
#列方向に結合 hstack(array1, array2)
col_stack = np.hstack((sample_5, sample_6))
print(col_stack)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [92]:
#配列の分割 split
sample_7 = np.arange(0,40).reshape(8,5)
print(sample_7)
#2より手前まで(0-1), 2から4の手前まで(2-3), 4から5の手前まで(4), 5以降(5-7) 
a1, a2, a3, a4 = np.split(sample_7, [2,4,5]) #デフォルトは行方向に分割
print('a1=\n', a1, '\n')
print('a2=\n', a2, '\n')
print('a3=\n', a3, '\n')
print('a4=\n', a4, '\n')
#1より手前まで(0), 1から3の手前まで(1-2), 3以降(3-4) 
b1, b2, b3 = np.split(sample_7, [1,3], axis=1) #列方向に分割
print('b1=\n', b1, '\n')
print('b2=\n', b2, '\n')
print('b3=\n', b3, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
a1=
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

a2=
 [[10 11 12 13 14]
 [15 16 17 18 19]] 

a3=
 [[20 21 22 23 24]] 

a4=
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

b1=
 [[ 0]
 [ 5]
 [10]
 [15]
 [20]
 [25]
 [30]
 [35]] 

b2=
 [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]
 [26 27]
 [31 32]
 [36 37]] 

b3=
 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]
 [33 34]
 [38 39]] 



In [95]:
#繰り返し処理
sample_8 = np.arange(1,4)
print(sample_8)
sample_8.repeat(5)

[1 2 3]


array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [110]:
#ブロードキャスト 配列の大きさが異なる場合に自動的に要素をコピーして対象の大きさを揃える
sample_9 = np.arange(1,10)
print(sample_9)
#スカラー値を1次元配列に展開
sample_9 * 10
print(sample_9 * 10)
#多次元配列でも同様
sample_A = np.arange(1,37).reshape(6,6)
print(sample_A + 100)
print(sample_A ** (1/2))

[1 2 3 4 5 6 7 8 9]
[10 20 30 40 50 60 70 80 90]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]
 [125 126 127 128 129 130]
 [131 132 133 134 135 136]]
[[1.    1.414 1.732 2.    2.236 2.449]
 [2.646 2.828 3.    3.162 3.317 3.464]
 [3.606 3.742 3.873 4.    4.123 4.243]
 [4.359 4.472 4.583 4.69  4.796 4.899]
 [5.    5.099 5.196 5.292 5.385 5.477]
 [5.568 5.657 5.745 5.831 5.916 6.   ]]
